name: Exemplo de workflow manual
on: [workflow_dispatch]  # permite rodar manualmente
permissions:
  contents: write
jobs:
  build: 
    name: Exemplo de workflow manual
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout code
        uses: actions/checkout@v4

      - name: Step 2 - Exemplo de workflow manual
        uses: grafana/k6-action@v0.2.0
        with: 
          filename: 1_smoke_test/smoke2.js

      - name: Step 3 - Prepare scripts folder and move report
        run: |
          ls -l
          mkdir -p 1_smoke_test
          mv index.html evidencias_test/

      - name: Step 4 - Upload performance test report
        uses: actions/upload-artifact@v4
        with: 
          name: relatorio-de-testes-de-performance
          path: evidencias_test/index.html
