name: Exemplo de workflow manual
on: [workflow_dispatch]
permissions:
  contents: write
jobs:
  build: 
    name: Exemplo de workflow manual
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout code
        uses: actions/checkout@v4

      - name: Step 2 - Executar teste com k6
        uses: grafana/k6-action@v0.2.0
        with: 
          filename: 1_smoke_test/smoke2.js

      - name: Step 3 - Preparar pasta de evidências e mover relatório
        run: |
          mkdir -p evidencias_test
          mv index.html evidencias_test/

      - name: Step 4 - Upload de artefato para download
        uses: actions/upload-artifact@v4
        with: 
          name: relatorio-de-testes-de-performance
          path: evidencias_test/index.html

      - name: Step 5 - Commit evidência no repositório
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add evidencias_test/index.html
          git commit -m "chore: adiciona evidência de teste k6"
          git push
